app/models.py
from datetime import datetime, timezone
from typing import Optional
import sqlalchemy as sa
import sqlalchemy.orm as so
from sqlalchemy import Table, Column, ForeignKey, ARRAY
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from slugify import slugify


tags_table = Table(
    'tags_assocation', db.metadata,
    sa.Column('post_id', sa.Integer(), sa.ForeignKey('post.id'), primary_key=True),
    sa.Column('tag_id', sa.Integer(), sa.ForeignKey('tag.id'), primary_key=True)
)

class User(UserMixin, db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    username: so.Mapped[str] = so.mapped_column(sa.String(64), index=True,
                                                unique=True)
    email: so.Mapped[str] = so.mapped_column(sa.String(120), index=True,
                                             unique=True)
    password_hash: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256))

    posts: so.WriteOnlyMapped['Post'] = so.relationship(
        back_populates='author')

    def __repr__(self):
        return '<User {}>'.format(self.username)
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)
    
class Tag(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    name: so.Mapped[str] = so.mapped_column(sa.String(64), index=True)
    posts: so.WriteOnlyMapped['Post'] = so.relationship(secondary=tags_table, back_populates='tags')

    def __repr__(self):
        return f'<Tag> {self.name}'
    
class Post(db.Model):
    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    title: so.Mapped[str] = so.mapped_column(sa.String(128))
    slug: so.Mapped[str] = so.mapped_column(sa.String(128), index=True, default='', nullable=True)
    body: so.Mapped[str] = so.mapped_column(sa.Text())
    timestamp: so.Mapped[datetime] = so.mapped_column(
        index=True, default=lambda: datetime.now(timezone.utc))
    user_id: so.Mapped[int] = so.mapped_column(sa.ForeignKey(User.id),
                                               index=True)
    
    tags: so.Mapped[Tag] = so.relationship(secondary=tags_table, back_populates='posts')
    author: so.Mapped[User] = so.relationship(back_populates='posts')

    def __repr__(self):
        return '<Post {}>'.format(self.body)
    
    def __init__(self, title, body, tags, author):
        self.body = body
        self.title = title
        self.slug = slugify(title)
        self.tags = tags
        self.author = author

@login.user_loader
def load_user(id):
    return db.session.get(User, int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_ckeditor import CKEditorField

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    body = CKEditorField('Body', validators=[DataRequired()])
    tags = StringField('Tags', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from flask_mail import Mail
from flask_moment import Moment
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os
from flask_ckeditor import CKEditor


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Please log in to access this page'
mail = Mail()
moment = Moment()
ckeditor = CKEditor()

def create_app(config_class=Config):

    app = Flask(__name__)
    app.config.from_object(Config)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    #mail.init_app(app)
    #moment.init_app(app)
    ckeditor.init_app(app)
    
    return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, url_for, redirect, flash, abort, request, current_app
from app import db
from app.main import bp
from app.models import User, Post, Tag
from app.main.forms import PostForm
import sqlalchemy as sa
from flask_login import login_required, current_user

@bp.route('/', methods=["GET"])
@bp.route('/index', methods=["GET"])
def index():
    user = db.session.scalar(sa.select(User, 1))
    query = user.posts.select().order_by(Post.timestamp.desc())
    page = request.args.get('page', 1, type=int)
    posts = db.paginate(query, page=page, per_page=current_app.config['POSTS_PER_PAGE'], error_out=False)
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template('index.html', title='Home', user=user, posts=posts.items,
                           next_url=next_url, prev_url=prev_url)

@bp.route('/about')
def about():
    return render_template('about.html', title="About")


@bp.route('/post/create', methods=["GET", "POST"])
@login_required
def create():
    form = PostForm()
    if not current_user.is_authenticated:
        return redirect(url_for('main.index'))
    if form.validate_on_submit():
        post = Post(title = form.title.data, body = form.body.data, tags = Tag(name=form.tags.data), author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post is now live!')
        return redirect(url_for('main.index'))
    return render_template('create_post.html', title='New Post', form=form)

@bp.route('/post/<slug>', methods=["GET"])
def view(slug):
    post = db.first_or_404(sa.select(Post).where(Post.slug == slug))
    return render_template('view_post.html', post=post, title=post.title)

@bp.route('/post/edit/<slug>', methods=["GET", "POST"])
@login_required
def edit(slug):
    post = db.first_or_404(sa.select(Post).where(Post.slug == slug))
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.tags = form.tags.data
        db.session.commit()
        flash('Your changes have been saved')
        return redirect(url_for('main.view', slug=post.slug))
    elif request.method == "GET":
        form.title.data = post.title
        form.body.data = post.body
        form.tags.data = post.tags
    return render_template('edit_post.html', title='Edit Post', post=post, form=form)

@bp.route('/post/delete/<slug>', methods=["GET", "POST"])
@login_required
def delete(slug):
    post = db.first_or_404(sa.select(Post).where(Post.slug == slug))
    form = PostForm()
    if form.validate_on_submit():
        db.session.delete(post)
        db.session.commit()
        flash('Your post has been deleted')
        return redirect(url_for('main.index'))
    elif request.method == "GET":
        form.title.data = post.title
        form.body.data = post.body
    return render_template('delete_post.html', title='Delete Post', post=post, form=form)

app/templates/_post.html
<div class="header">
    <h2><a class="nostyle" href="{{url_for('main.view', slug = post.slug)}}">{{post.title}}</a>
        {% if current_user.is_authenticated %}
        <a href="{{url_for('main.edit', slug=post.slug)}}" class="edit_btn">[edit]</a>
        <a href="{{url_for('main.delete', slug=post.slug)}}" class="delete_btn">[delete]</a>{% endif %}
    </h2>
    <p class="byline">by {{post.author.username}} on
        {{post.timestamp.month}}/{{post.timestamp.day}}/{{post.timestamp.year}} tagged under
        <span class="tag">{{post.tags.name}}</span>
    </p>
</div>

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div>
    About page
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }} - Blog</title>
    {% else %}
    <title>Welcome to my blog!</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar shadow-lg navbar-expand-lg">
        <div class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="navbar-brand" href="{{ url_for('main.index') }}">EmilTobin.com</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                </li>
                {% if current_user.is_anonymous %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.create') }}">Create Post</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav align-items-end">
                <li>
                    <a class="nav-link" href="https://github.com/emil-of-the-field/"><img
                            src="{{ url_for('static', filename='images/github-mark-white.png') }}" alt="Github"
                            width="32" height="32"></a>
                </li>
                <li>
                    <a class="nav-link" href="https://app.thestorygraph.com/profile/digitalpusheen"><img
                            src="{{ url_for('static', filename='images/storygraph.svg') }}" alt="StoryGraph" width="32"
                            height="32"></a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="row">

            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            {% endwith %}
            <div class="content col-9">
                <div class="main">
                    {% block content %}{% endblock %}
                </div>
            </div>
            <div class="col-3">
                <div class="card">
                    <div class="card-header text-center">Latest Posts</div>
                    <div class="card-text"></div>
                    {% set sorted_posts = get_ordered_posts() %}
                    <ul class="list-group">
                        {% for post in sorted_posts[:10] %}
                        <li class="list-group-item">
                            <a class="" href="{{url_for('main.view', slug = post.slug)}}">{{ post.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="card">
                    <div class="card-header text-center">Search Posts by Tag</div>

                </div>

</body>

</html>

app/templates/create_post.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>New Post</h1>

    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=32) }}
            {% for error in form.body.errors %}
            <span style="color: red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.body.label }}<br>
            {{ form.body() }}
            {% for error in form.body.errors %}
            <span style="color: red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p> {{ form.tags.label}}<br>
            {{ form.tags(size=32)}}</p>
        <p>{{ form.submit(class="btn btn-primary") }}</p>
    </form>
</div>

{{ ckeditor.load() }}
{{ ckeditor.config(name='body')}}
{% endblock %}

app/templates/delete_post.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Delete Post</h1>

    <form action="" method="post" onsubmit="return confirm ('Are you sure you want to delete this post?')" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=32) }}
            {% for error in form.body.errors %}
            <span style="color: red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.body.label }}<br>
            {{ form.body() }}
            {% for error in form.body.errors %}
            <span style="color: red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit(value="Delete", class="btn btn-danger") }}</p>
    </form>
</div>

{{ ckeditor.load() }}
{{ ckeditor.config(name='body')}}
{% endblock %}

app/templates/edit_post.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Edit Post</h1>

    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p>
            {{ form.title.label }}<br>
            {{ form.title(size=32) }}
            {% for error in form.body.errors %}
            <span style="color: red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.body.label }}<br>
            {{ form.body() }}
            {% for error in form.body.errors %}
            <span style="color: red">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p> {{ form.tags.label}}<br>
            {{ form.tags(size=32)}}</p>
        <p>{{ form.submit(class="btn btn-primary") }}</p>
    </form>
</div>

{{ ckeditor.load() }}
{{ ckeditor.config(name='body')}}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content%}

{% for post in posts%}

<div class="post">
    {% include '_post.html' %}
    {% set snippet = post.body[0:500] %}
    {% if post.body | length > 500 %}
    {% set snippet = snippet + '...' %}
    <p class="snippet">{{ snippet|safe }}</p>
    <p><a href="{{url_for('main.view', slug = post.slug)}}">Continue reading post</a></p>
    {% else %}
    <p class="snippet">{{ snippet|safe }}</p>
    {% endif %}
</div>

{% endfor %}

{% if prev_url %}
<a href="{{ prev_url }}"> Newer Posts</a>
{% endif %}
{% if next_url %}
<a href="{{ next_url }}">Older Posts</a>
{% endif %}

{% endblock %}

app/templates/view_post.html
{% extends 'base.html' %}

{% block content%}
<div class="post">
    {% include '_post.html' %}
    <p class="body">{{post.body | safe}}</p>
</div>


{% endblock %}